### PR TITLE
chore: fix test cases & clean up docs

### PR DESCRIPTION
**Pull request by Lexpeartha**
PR to clean up where it's possible, and to fix failing CI

### CODE REVIEW

**Comment by azrikahar** [comment]
Hi, random tangent here but should the test ci be stopped manually first? It seems like it's somehow stuck & keeps running instead of stopping itself.

**Comment by Lexpeartha** [comment]
image
Looking into it, but on my local machine everything works fine

**Comment by Lexpeartha** [comment]
Alright, it seems that newer versions of `playwright` require additional step to set up browser appropriate to OS it's running on

**Comment by Lexpeartha** [comment]
@danielroe One question, in other PR I saw you pinned `nuxt` version to rc 8, is there a particular reason for that? Should I update it, or leave it like this?

**Comment by azrikahar** [comment]
> Alright, it seems that newer versions of `playwright` require additional step to set up browsers appropriate to OS it's running on

Interesting! Glad it's resolved now 🚀

**Comment by danielroe** [comment]
Yes, we'll leave it pinned for docs at the moment, unless you'd like to tackle upgrading docus... you can see https://github.com/unjs/nitro/pull/365 as an example...

**Comment by Lexpeartha** [comment]
> unless you'd like to tackle upgrading docus... you can see [unjs/nitro#365](https://github.com/unjs/nitro/pull/365) as an example...

I think we can merge this PR, and I'll start migration in new one 👌🏽

**Pull request merged**
