### PR TITLE
refactor: use kit rc10 utilities

### PR DESCRIPTION
**Pull request by Lexpeartha**

### CODE REVIEW

**Comment by Lexpeartha** [comment]
Also, do you want me to upgrade docus in this, or another PR?

**Comment by danielroe** [comment]
Let's wait for another PR.

**Comment by danielroe** [comment]
Actually, it seems that the docs are broken in this PR (not your fault!) so maybe we have to resolve at the same time.

**Comment by Lexpeartha** [comment]
weird, locally docs work fine for me

**Comment by Lexpeartha** [comment]
Just to confirm if I understood things correctly, docus in now implement as a nuxt theme, correct?

**Comment by Lexpeartha** [comment]
Alright, I'll merge these changes then, and leave upgrading docus for another time

**Comment by danielroe** [comment]
If we merge these changes, unfortunately the docs will be broken.

**Comment by Lexpeartha** [comment]
I reverted last commit, vercel build seems to be working now, no?

**Comment by danielroe** [comment]
Yep - sorry, didn't spot it.

**Review by danielroe — APPROVED** [review]

**Pull request merged**
